#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# add_course:
#     path:       /api/course/create
#     controller: App\Controller\CourseController::addCourse
#     methods:    POST